### ISSUE TITLE
Auto instrumentation fails, if multiple functions contain the same parametrised layers stanza

### ISSUE THREAD

**Issue by zboris** [iopipe/serverless-iopipe-layers#3]
serverless.yml
```
func-one:
  handler: func-one.handler
  layers: ${self:custom.layers.common.${self:provider.stage}, self:custom.layers.common.default}
  events:
    - http:
        path: one
        method: get
        integration: lambda-proxy
func-two:
  handler: func-two.handler
  layers: ${self:custom.layers.common.${self:provider.stage}, self:custom.layers.common.default}
  events:
    - http:
        path: two
        method: get
        integration: lambda-proxy
```
Serverless transforms it to
```
  func-one:
    handler: func-one.handler
    layers:
      - >-
        arn:aws:lambda:some-region:some-account:layer:somelayername:1

  func-two:
    handler: func-two.handler
    layers:
      $ref: '$["functions"]["func-one"]["layers"]'
```
iopipe plugin fails to add its layers to the func-two, since it has been added via func-one reference already, resulting in no layers, and IOPIPE instrumentation in the func-two and spits out an error message:
`Function "func-two" already specifies an IOpipe layer, skipping`
